CREATE TABLE PARENTS (ID INTEGER NOT NULL);
CREATE TABLE CHILDREN (ID INTEGER NOT NULL, PARENT_ID INTEGER);

ALTER TABLE PARENTS ADD CONSTRAINT PARENTS_PK PRIMARY KEY (ID);
ALTER TABLE CHILDREN ADD CONSTRAINT CHILDREN_PK PRIMARY KEY (ID);

ALTER TABLE CHILDREN ADD CONSTRAINT CHILDREN_PARENTS_FK FOREIGN KEY (PARENT_ID) REFERENCES PARENTS (ID);
